# Context System Configuration
# This file defines configuration defaults for the agent-context system

system:
  schema_version: "1.0.0"
  created_date: "2025-07-11"

linter:
  warning_days_old: 90          # Warn if document not modified for this many days
  warning_days_until_expire: 7  # Warn if document expires within this many days
  
qdrant:
  version: "1.14.x"
  host: "localhost"
  port: 6333
  collection_name: "project_context"
  embedding_model: "text-embedding-ada-002"
  ssl: false  # Enable in production
  verify_ssl: true
  timeout: 30
  
neo4j:
  version: "5.x"
  host: "localhost"
  port: 7687
  database: "context_graph"
  ssl: false  # Enable in production
  verify_ssl: true
  timeout: 30

redis:
  version: "7.x"
  host: "localhost"
  port: 6379
  database: 0
  ssl: false  # Enable in production
  verify_ssl: true
  timeout: 30
  max_connections: 50
  # Key prefixes for different data types
  prefixes:
    session: "session:"
    cache: "cache:"
    lock: "lock:"
    metric: "metric:"
    state: "state:"

duckdb:
  version: "0.10.x"
  database_path: "context/.duckdb/analytics.db"
  memory_limit: "2GB"
  threads: 4
  # Analytics tables
  tables:
    metrics: "context_metrics"
    events: "context_events"
    summaries: "context_summaries"
    trends: "context_trends"
  
storage:
  retention_days: 90
  archive_path: "context/archive"
  
agents:
  cleanup:
    schedule: "0 2 * * *"  # Daily at 2 AM
    expire_after_days: 30
  
  doc_agent:
    auto_update_metadata: true
    
  pm_agent:
    sprint_duration_days: 14
    
evaluation:
  cosine_threshold: 0.85
  schema_compliance_threshold: 1.0
  
security:
  sigstore_enabled: true
  ipfs_pinning: false
  
mcp:
  contracts_path: "context/mcp_contracts"
  rpc_timeout_seconds: 30