# Context System Configuration
# This file defines configuration defaults for the agent-context system

system:
  schema_version: "1.0.0"
  created_date: "2025-07-11"

linter:
  warning_days_old: 90          # Warn if document not modified for this many days
  warning_days_until_expire: 7  # Warn if document expires within this many days
  
qdrant:
  version: "1.14.x"
  host: "localhost"
  port: 6333
  collection_name: "project_context"
  embedding_model: "text-embedding-ada-002"
  
neo4j:
  version: "5.x"
  host: "localhost"
  port: 7687
  database: "context_graph"
  
storage:
  retention_days: 90
  archive_path: "context/archive"
  
agents:
  cleanup:
    schedule: "0 2 * * *"  # Daily at 2 AM
    expire_after_days: 30
  
  doc_agent:
    auto_update_metadata: true
    
  pm_agent:
    sprint_duration_days: 14
    
evaluation:
  cosine_threshold: 0.85
  schema_compliance_threshold: 1.0
  
security:
  sigstore_enabled: true
  ipfs_pinning: false
  
mcp:
  contracts_path: "context/mcp_contracts"
  rpc_timeout_seconds: 30