---
# YAML linting config specifically for Yamale schema files
# Allows patterns required by Yamale validation framework
extends: default

rules:
  # Allow longer lines for complex schema definitions
  line-length:
    max: 120
    level: warning

  # Multi-document files are required by Yamale
  document-start: disable
  document-end: disable

  # Yamale schemas may have function-like syntax
  colons:
    max-spaces-after: 1

  # Allow flexible indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments formatting
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Brackets for Yamale functions
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Don't require quotes on keys that look like booleans
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    level: warning

  # Allow empty values (common in schemas)
  empty-values: enable

  # Key ordering not enforced
  key-ordering: disable
