---
# Local development overrides
# This file is automatically used by `docker-compose up` for local development
services:
  # Development-specific configurations can be added here
  # For example, mounting local volumes for live development

  qdrant:
    # Development-specific Qdrant settings
    environment:
      - QDRANT__LOG_LEVEL=INFO

  neo4j:
    # Development-specific Neo4j settings
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/devpassword}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_logs_debug_level=INFO

  redis:
    # Development-specific Redis settings
    command: >
      redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
      --loglevel notice
