---
vector_db:
  embedding:
    batch_size: 100
    max_retries: 3
    initial_retry_delay: 1.0
    retry_backoff_factor: 2.0
    request_timeout: 30
  search:
    default_limit: 10
    max_limit: 100
    ef_search: 128
  indexing:
    flush_interval_sec: 5
    max_segment_size: 200000
    memmap_threshold: 100000
  cache:
    enabled: true
    max_entries: 10000
    ttl_seconds: 3600
graph_db:
  connection_pool:
    min_size: 1
    max_size: 10
    acquisition_timeout: 60
  query:
    max_path_length: 5
    default_limit: 50
    query_timeout: 30
    use_query_cache: true
  batch:
    size: 1000
    parallel_transactions: 4
  algorithms:
    pagerank_iterations: 20
    community_detection_resolution: 1.0
search:
  ranking:
    temporal_decay_days: 30
    temporal_decay_rate: 0.01
    type_boosts:
      architecture: 1.25
      design: 1.2
      decision: 1.15
      sprint: 1.1
      api: 1.0
      test: 0.9
      documentation: 0.85
  graphrag:
    max_graph_hops: 2
    context_weight: 0.3
    min_similarity_threshold: 0.7
resources:
  max_memory_gb: 4
  max_cpu_percent: 80
  disk_cache_size_gb: 10
kv_store:
  redis:
    connection_pool:
      min_size: 5
      max_size: 50
      timeout: 5
    cache:
      ttl_seconds: 3600
      max_entries: 10000
    pipeline:
      batch_size: 100
      flush_interval_ms: 50
  duckdb:
    batch_insert:
      size: 1000
      timeout_seconds: 30
    query:
      timeout_seconds: 60
      max_results: 10000
    analytics:
      aggregation_interval: 5 minutes
      retention_days: 90
monitoring:
  metrics_enabled: true
  metrics_interval_seconds: 60
  slow_query_threshold_ms: 1000
  log_level: INFO
