---
schema_version: "1.0"
enforcement:
  allow_bypass: true
  enabled: true
  require_state_file: true
  strict_mode: true
branch_patterns:
  # List of allowed branch prefixes for PR validation
  prefixes:
    - fix
    - feature
    - hotfix
    - refactor
    - chore
    - docs
    - style
    - test
  # Optional custom regex pattern for complex branch naming
  # Use {issue} placeholder for issue number
  # Example: "issue-{issue}-.*" would match "issue-123-fix-bug"
  custom_regex: null
  # PR list limit for busy repositories
  pr_list_limit: 100
phases:
  implementation:
    max_duration_hours: 8
    prevent_on_main: true
    required_outputs:
      - branch_created
      - implementation_complete
      - commits_made
  investigation:
    max_duration_hours: 4
    required_outputs:
      - scope_clarity
      - investigation_completed
    skippable_if:
      - scope_is_clear
  monitoring:
    max_wait_hours: 48
    required_outputs:
      - pr_monitoring_active
  planning:
    max_duration_hours: 2
    required_files:
      - context/trace/task-templates/issue-{issue_number}-*.md
      - context/trace/scratchpad/*-issue-{issue_number}-*.md
    required_outputs:
      - task_template_created
      - scratchpad_created
      - documentation_committed
  pr_creation:
    max_duration_hours: 1
    required_labels:
      - workflow-enforced
    required_outputs:
      - pr_created
      - branch_pushed
      - documentation_included
  validation:
    max_duration_hours: 2
    min_coverage: 71.82
    required_commands:
      - ./scripts/run-ci-docker.sh
      - pre-commit run --all-files
    required_outputs:
      - tests_run
      - ci_passed
      - coverage_maintained
    ci_validation:
      require_ci: true
      max_age_hours: 0  # 0 = no time limit, >0 = hours before stale
      marker_files:
        - .last-ci-run
        - ci-output.log
        - .pytest_cache/v/cache/lastfailed
        - coverage.xml
      allow_test_only: false  # Allow validation with tests but no CI
