---
# CI Optimization Configuration
# Central configuration for all CI optimization features

version: "1.0"
schema_version: "2024.1"

# Global optimization settings
optimization:
  enabled: true
  mode: "opt-in"  # opt-in, opt-out, always
  performance_target:
    execution_time_reduction: 50  # Percentage reduction target
    cache_hit_rate: 80  # Target cache hit rate percentage
    parallel_efficiency: 85  # Target parallel execution efficiency

# Caching configuration
cache:
  enabled: true
  backend: "local"  # local, redis, s3

  local:
    cache_dir: ".ci-cache"
    max_size_mb: 5000  # 5GB default
    compression: true

  redis:
    url: "redis://localhost:6379"
    ttl_hours: 168  # 1 week
    key_prefix: "ci-cache:"

  s3:
    bucket: "ci-cache-bucket"
    prefix: "cache/"
    region: "us-west-2"

  # What to cache
  targets:
    dependencies: true
    build_artifacts: true
    test_results: true
    docker_layers: true
    npm_modules: true
    pip_packages: true

  # Cache invalidation rules
  invalidation:
    on_dependency_change: true
    max_age_hours: 720  # 30 days
    cleanup_frequency: "daily"

# Distributed CI configuration
distributed:
  enabled: false  # Opt-in feature
  coordinator:
    redis_url: "redis://localhost:6379"
    job_queue_size: 1000
    heartbeat_interval: 30  # seconds
    runner_timeout: 120  # seconds

  runners:
    auto_discovery: true
    capacity_multiplier: 1.0  # Adjust runner capacity
    load_balancing: "least_loaded"  # least_loaded, round_robin

  # Job scheduling
  scheduling:
    priority_levels: 3
    timeout_default: 3600  # 1 hour
    retry_max: 2
    parallel_limit: 10  # Max parallel jobs per runner

# Incremental build configuration
incremental:
  enabled: true

  # Language-specific settings
  languages:
    python:
      enabled: true
      dependency_tracking: true
      test_selection: "affected"  # all, affected, none
      type_checking: "incremental"

    javascript:
      enabled: true
      build_cache: true
      test_selection: "affected"
      transpilation: "incremental"

    typescript:
      enabled: true
      build_cache: true
      type_checking: "incremental"
      test_selection: "affected"

    docker:
      enabled: true
      layer_caching: true
      multi_stage_optimization: true

  # Change detection
  change_detection:
    method: "git"  # git, hash, timestamp
    base_ref: "origin/main"
    ignore_patterns:
      - "*.md"
      - "docs/**"
      - ".github/workflows/**"
      - "*.log"

  # Build optimization
  build:
    parallel_builds: true
    dependency_ordering: true
    artifact_reuse: true

# Hardware support configuration
hardware:
  gpu:
    enabled: false  # Opt-in feature
    detection: "auto"  # auto, manual, disabled
    job_routing: "capability_based"
    cost_optimization: true

  specialized:
    large_memory: false
    high_cpu: false
    ssd_storage: false

  # Resource limits
  limits:
    cpu_cores: null  # null = auto-detect
    memory_gb: null  # null = auto-detect
    disk_space_gb: 100

# Analytics and monitoring configuration
analytics:
  enabled: true

  # Metrics collection
  metrics:
    execution_times: true
    cache_performance: true
    resource_utilization: true
    success_rates: true
    cost_tracking: true

  # Dashboard configuration
  dashboard:
    enabled: true
    port: 8080
    refresh_interval: 30  # seconds
    retention_days: 90

  # Export configuration
  export:
    format: "json"  # json, csv, prometheus
    endpoint: null  # Optional external endpoint
    frequency: "hourly"

  # Alerting
  alerts:
    performance_degradation: true
    cache_miss_threshold: 30  # Percent
    failure_rate_threshold: 10  # Percent

# Integration settings
integrations:
  # GitHub Actions integration
  github_actions:
    enabled: true
    workflow_optimization: true
    cache_sharing: true
    parallel_jobs: true

  # Docker integration
  docker:
    enabled: true
    buildkit: true
    layer_caching: true
    multi_platform: false

  # Container registry
  registry:
    cache_images: true
    multi_arch: false
    compression: true

# Security and safety settings
security:
  # Cache security
  cache_encryption: false
  access_control: true
  audit_logging: true

  # Distributed security
  runner_authentication: true
  job_isolation: true
  network_security: true

  # Resource limits for safety
  resource_limits:
    max_cache_size_per_job: 1000  # MB
    max_execution_time: 7200  # 2 hours
    max_parallel_jobs: 20

# Compatibility and fallback settings
compatibility:
  # Fallback behavior when optimizations fail
  fallback_mode: "standard_ci"  # standard_ci, fail_fast, continue

  # Legacy support
  legacy_workflows: true
  gradual_migration: true

  # Environment compatibility
  environments:
    development: true
    staging: true
    production: false  # Conservative default

# Performance tuning
performance:
  # Concurrency settings
  max_concurrent_builds: 4
  max_concurrent_tests: 8
  max_concurrent_uploads: 2

  # Memory management
  memory_limits:
    cache_manager: 512  # MB
    build_processes: 1024  # MB
    test_processes: 2048  # MB

  # Network optimization
  network:
    download_parallelism: 4
    upload_parallelism: 2
    retry_attempts: 3
    timeout_seconds: 300

# Debugging and development
debug:
  enabled: false
  verbose_logging: false
  performance_profiling: false
  cache_debugging: false

  # Debug outputs
  save_intermediate_results: false
  export_dependency_graph: false
  benchmark_comparisons: false

# Feature flags for gradual rollout
feature_flags:
  advanced_caching: false
  distributed_execution: false
  gpu_acceleration: false
  predictive_building: false
  ai_optimization: false

  # Experimental features
  experimental:
    smart_test_selection: false
    build_prediction: false
    resource_forecasting: false
    adaptive_parallelism: false

# Maintenance and cleanup
maintenance:
  # Automated cleanup
  auto_cleanup: true
  cleanup_schedule: "0 2 * * *"  # Daily at 2 AM

  # Cache maintenance
  cache_cleanup:
    remove_unused: true
    compress_old: true
    archive_threshold_days: 30

  # Log rotation
  log_rotation:
    enabled: true
    max_size_mb: 100
    max_files: 10
    compress: true
