name: Verify CI Results
description: Verify local CI results in GitHub Actions
inputs:
  mode:
    description: 'Verification mode: parallel, verifier-only, or traditional'
    required: false
    default: parallel
runs:
  using: composite
  steps:
  - name: Verify Results
    shell: bash
    run: "\nif [ \"${{ inputs.mode }}\" = \"traditional\" ]; then\n  echo \"Running\
      \ in traditional mode - skipping verification\"\n  exit 0\nfi\n\necho \"\U0001F50D\
      \ Verifying CI results (mode: ${{ inputs.mode }})\"\n\n# Check for CI results\
      \ artifact\nif [ ! -f \"ci-results.json.gpg\" ]; then\n  echo \"\u274C No CI\
      \ results found - push must run local CI first\"\n  exit 1\nfi\n\n# Verify GPG\
      \ signature\npython scripts/verify-ci-results.py --file ci-results.json.gpg\
      \ || exit 1\n\n# In parallel mode, also run GitHub CI for comparison\nif [ \"\
      ${{ inputs.mode }}\" = \"parallel\" ]; then\n  echo \"Running GitHub CI for\
      \ comparison...\"\n  # This would normally trigger the actual CI jobs\nfi\n"
