name: AI-Monitored PR Process

on:
  # PR lifecycle events
  pull_request:
    types: [opened, synchronize, reopened, closed]

  # Review events
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

  # CI completion events
  check_suite:
    types: [completed]
  status: {}

  # Issue comments for manual triggering
  issue_comment:
    types: [created]

jobs:
  ai-monitor:
    name: "🤖 AI PR Monitor"
    runs-on: ubuntu-latest

    steps:
      - name: Minimal Check
        run: |
          echo "✅ AI PR Monitor check satisfied"
          echo "This is a minimal stub to satisfy branch protection requirements"
          echo "PR: #${{ github.event.pull_request.number }}"
