name: Context Lint

on:
  push:
    paths:
      - 'context/**/*.yaml'
      - 'context_lint.py'
      - '.ctxrc.yaml'
  pull_request:
    paths:
      - 'context/**/*.yaml'
      - 'context_lint.py'
      - '.ctxrc.yaml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click yamale pyyaml
    
    - name: Check configuration
      run: python context_lint.py check-config --verbose
    
    - name: Validate context files
      run: python context_lint.py validate context/ --verbose
    
    - name: Show context statistics
      run: python context_lint.py stats context/
      
    - name: Run cleanup agent (dry run)
      run: python cleanup_agent.py --dry-run --verbose