name: Context Lint

on:
  push:
    paths:
      - 'context/**/*.yaml'
      - 'context_lint.py'
      - '.ctxrc.yaml'
      - '**/*.py'
      - 'pyproject.toml'
      - 'mypy.ini'
  pull_request:
    paths:
      - 'context/**/*.yaml'
      - 'context_lint.py'
      - '.ctxrc.yaml'
      - '**/*.py'
      - 'pyproject.toml'
      - 'mypy.ini'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      - name: Check configuration
        run: python -m src.agents.context_lint check-config --verbose

      - name: Validate context files
        run: python -m src.agents.context_lint validate context/ --verbose

      - name: Show context statistics
        run: python -m src.agents.context_lint stats context/

      - name: Check Python formatting with Black
        run: |
        black --check --diff .

      - name: Run type checking with mypy
        run: |
        mypy . --config-file mypy.ini || true  # Allow failures initially

      - name: Run cleanup agent (dry run)
        run: python -m src.agents.cleanup_agent --dry-run --verbose
